status = [
  "cargo test (stable, i686-pc-windows-msvc, windows-latest)",
  "cargo test (stable, i686-unknown-linux-gnu, ubuntu-latest)",
  "cargo test (stable, x86_64-apple-darwin, macos-latest)",
  "cargo test (stable, x86_64-pc-windows-msvc, windows-latest)",
  "cargo test (stable, x86_64-unknown-linux-gnu, ubuntu-latest)",
  "cargo test (beta, x86_64-unknown-linux-gnu, ubuntu-latest)",
  "cargo test (nightly, x86_64-unknown-linux-gnu, ubuntu-latest)",
  "cargo hack check --each-feature",
  "cargo build --update",
  "cargo fmt --check",
  "cargo clippy",
  "codecov",
  "docs.rs",
  "cargo audit",
]
delete_merged_branches = true
